# Generated by Django 2.0.2 on 2018-03-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, verbose_name='開始日')),
                ('staff', models.CharField(choices=[('きゅう', 'きゅう'), ('スタッフA', 'スタッフA'), ('スタッフB', 'スタッフB')], default='きゅう', max_length=100, verbose_name='担当者')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='内容')),
                ('status', models.CharField(choices=[('着手', '着手'), ('実装', '実装'), ('完了', '完了')], default='着手', max_length=100, verbose_name='ステータス')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Project')),
            ],
        ),
    ]
